#!/bin/bash
# ============================================
# Atlas + OpenClaw Entrypoint for Salad Cloud
# ============================================
# Starts OpenClaw gateway in the background,
# then runs the Atlas service in the foreground.
# ============================================

set -e

echo "============================================"
echo " ATLAS + OpenClaw on Salad Cloud"
echo "============================================"

# --- Generate OpenClaw .env from container env vars ---
# This allows configuring OpenClaw entirely through Salad Cloud
# environment variables, without SSH or interactive setup.
OPENCLAW_ENV_FILE="${OPENCLAW_HOME:-/home/atlas/.openclaw}/.env"

echo "# Auto-generated by Atlas entrypoint" > "${OPENCLAW_ENV_FILE}"

# LLM API keys - pass any of these via Salad Cloud env vars
[ -n "${ANTHROPIC_API_KEY}" ]   && echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> "${OPENCLAW_ENV_FILE}"
[ -n "${OPENAI_API_KEY}" ]      && echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> "${OPENCLAW_ENV_FILE}"
[ -n "${GEMINI_API_KEY}" ]      && echo "GEMINI_API_KEY=${GEMINI_API_KEY}" >> "${OPENCLAW_ENV_FILE}"
[ -n "${OPENROUTER_API_KEY}" ]  && echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}" >> "${OPENCLAW_ENV_FILE}"

# Gateway auth
[ -n "${OPENCLAW_GATEWAY_TOKEN}" ]    && echo "OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}" >> "${OPENCLAW_ENV_FILE}"
[ -n "${OPENCLAW_GATEWAY_PASSWORD}" ] && echo "OPENCLAW_GATEWAY_PASSWORD=${OPENCLAW_GATEWAY_PASSWORD}" >> "${OPENCLAW_ENV_FILE}"

# Channel tokens - pass these to enable channels
[ -n "${TELEGRAM_BOT_TOKEN}" ]  && echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" >> "${OPENCLAW_ENV_FILE}"
[ -n "${DISCORD_BOT_TOKEN}" ]   && echo "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}" >> "${OPENCLAW_ENV_FILE}"
[ -n "${SLACK_BOT_TOKEN}" ]     && echo "SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}" >> "${OPENCLAW_ENV_FILE}"

echo "OpenClaw .env written to ${OPENCLAW_ENV_FILE}"

# --- Start OpenClaw gateway in background ---
OPENCLAW_PORT="${OPENCLAW_GATEWAY_PORT:-18789}"
echo "Starting OpenClaw gateway on port ${OPENCLAW_PORT}..."

openclaw gateway \
  --port "${OPENCLAW_PORT}" \
  --allow-unconfigured \
  --bind lan \
  > /data/logs/openclaw.log 2>&1 &

OPENCLAW_PID=$!
echo "OpenClaw gateway started (PID: ${OPENCLAW_PID})"

# Graceful shutdown: forward signals to both processes
cleanup() {
  echo "Shutting down..."
  kill "${OPENCLAW_PID}" 2>/dev/null || true
  wait "${OPENCLAW_PID}" 2>/dev/null || true
  exit 0
}
trap cleanup SIGTERM SIGINT

# --- Start Atlas service in foreground ---
echo "Starting Atlas service..."
exec python3 -m cloud.salad_service
