# Self-Organizing Audio-Visual System Configuration

# System-level settings
system:
  multimodal_size: 10
  learning_rate: 0.01
  learning_rule: "oja"
  prune_interval: 1000
  structural_plasticity_interval: 2000

# Visual processor settings
visual:
  input_width: 24
  input_height: 24
  use_grayscale: true
  patch_size: 12
  stride: 12
  contrast_normalize: true
  layer_sizes: [12, 8, 4]

# Audio processor settings
audio:
  sample_rate: 22050
  window_size: 128
  hop_length: 96
  n_mels: 8
  min_freq: 50
  max_freq: 8000
  normalize: true
  layer_sizes: [10, 6, 4]

# AV capture settings
capture:
  video_width: 120
  video_height: 90
  fps: 30
  audio_channels: 1
  chunk_size: 128

# Monitoring and visualization settings
monitor:
  update_interval: 0.033
  save_snapshots: false
  snapshot_interval: 1000
  snapshot_path: "snapshots"

# Checkpointing settings
checkpointing:
  enabled: true
  checkpoint_interval: 1000  # Save every 100 frames for quicker checkpointing
  checkpoint_dir: "checkpoints"
  max_checkpoints: 3  # Number of most recent checkpoints to keep
  load_latest: true    # Enable automatic loading of the latest checkpoint
  save_on_exit: true  # Save checkpoint when program exits 